### ISSUE TITLE
Could not install with go get

### ISSUE THREAD

**Issue by dimiro1** [andrewarrow/paradise_ftp#1] opened 2016-03-17 23:41 UTC
I could not install the package with the standard ```$ go get github.com/andrewarrow/paradise_ftp```.

**Comment by ctrlrsf** [comment] 2016-03-21 14:15
Same. Here's my go get output:

```
$ go get github.com/andrewarrow/paradise_ftp
package paradise/server: unrecognized import path "paradise/server"
```

**Comment by yanpozka** [comment] 2016-03-21 17:23
I'm having the same issue, it seems the problem is in this line
https://github.com/andrewarrow/paradise_ftp/blob/d849dc401c4111488957a67c5dabb67761d45882/paradise.go#L6

It should be something like:
```go
"github.com/andrewarrow/paradise_ftp/server"
```

**Comment by dc0d** [comment] 2016-03-25 14:11
Same here; but even after manually change things & compile it, it does not seem working.

**Comment by ctrlrsf** [comment] 2016-03-29 18:03
Should be fixed by PR https://github.com/andrewarrow/paradise_ftp/pull/2

Specifically: https://github.com/andrewarrow/paradise_ftp/pull/2/files#diff-7ddfb3e035b42cd70649cc33393fe32cL6

```
$ go get github.com/buddhamagnet/paradise_ftp
$ echo $?
0
$ go install  github.com/buddhamagnet/paradise_ftp
$ paradise_ftp
listening on: localhost:2121
```

**Comment by andrewarrow** [comment] 2016-04-21 14:37
sorry for late reply, glad you'll solved this :)

Yeah I never tested "go get" because i'm using paradise as stand alone go program. Will fix in master soon.

**Comment by andrewarrow** [comment] 2016-04-22 00:46
fixed in master too.

**Closed by andrewarrow** 2016-04-22 00:46 UTC
